# Generated by Django 4.0.2 on 2022-06-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_sn', models.CharField(blank=True, max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=20)),
                ('org_code', models.CharField(blank=True, max_length=20)),
                ('homepage', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='homepage.homepage')),
            ],
            options={
                'ordering': ('org_code',),
            },
        ),
    ]
