# Generated by Django 4.0.2 on 2022-07-06 09:43

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('homepage', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settlement', serialize=False, to='homepage.homepage')),
                ('list_sn', models.CharField(blank=True, max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=20)),
                ('org_code', models.CharField(blank=True, max_length=20)),
                ('case_num', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=20)),
                ('ethnicity', models.CharField(blank=True, max_length=20)),
                ('id_type', models.CharField(blank=True, max_length=20)),
                ('id_card_num', models.CharField(blank=True, max_length=20)),
                ('profession', models.CharField(blank=True, max_length=20)),
                ('present_addr1', django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=20), default=None, max_length=63, size=3)),
                ('present_addr2', models.CharField(blank=True, max_length=20)),
                ('work_addr1', django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=20), default=None, max_length=63, size=3)),
                ('work_addr2', models.CharField(blank=True, max_length=20)),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('work_zip', models.CharField(blank=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=20)),
                ('contact_relation', models.CharField(blank=True, max_length=20)),
                ('contact_addr1', django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=20), default=None, max_length=63, size=3)),
                ('contact_addr2', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('newborn_birth_weight', models.FloatField(blank=True, default=0.0)),
                ('newborn_admit_weight', models.FloatField(blank=True, default=0.0)),
                ('admit_path', models.CharField(blank=True, max_length=20)),
                ('admit_specialty', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=63, size=3)),
                ('trans_specialty', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=63, size=3)),
                ('release_time', models.CharField(blank=True, max_length=20)),
                ('release_specialty', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=63, size=3)),
                ('hosp_duration', models.CharField(blank=True, max_length=20)),
                ('head_injury_check', models.BooleanField(blank=True, default=False)),
                ('release_type', models.CharField(blank=True, max_length=20)),
                ('cont_hosp_check', models.BooleanField(blank=True, default=False)),
                ('cont_hosp_plan', models.CharField(blank=True, max_length=20)),
                ('physician_name', models.CharField(blank=True, max_length=20)),
                ('nurse_ic_name', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('org_code',),
            },
        ),
        migrations.CreateModel(
            name='PreAdmitComa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, default=0)),
                ('hrs', models.IntegerField(blank=True, default=0)),
                ('mins', models.IntegerField(blank=True, default=0)),
                ('settlement', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pre_admit_coma', to='settlement.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='PostAdmitComa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, default=0)),
                ('hrs', models.IntegerField(blank=True, default=0)),
                ('mins', models.IntegerField(blank=True, default=0)),
                ('settlement', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_admit_coma', to='settlement.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='OtherOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('anaesthesia_type', models.CharField(blank=True, max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=20)),
                ('operator_code', models.CharField(blank=True, max_length=20)),
                ('anaesthetist_name', models.CharField(blank=True, max_length=20)),
                ('anaesthetist_code', models.CharField(blank=True, max_length=20)),
                ('op_time', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=42, size=2)),
                ('anaesthesia_time', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=42, size=2)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_ops', to='settlement.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='MainOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('anaesthesia_type', models.CharField(blank=True, max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=20)),
                ('operator_code', models.CharField(blank=True, max_length=20)),
                ('anaesthetist_name', models.CharField(blank=True, max_length=20)),
                ('anaesthetist_code', models.CharField(blank=True, max_length=20)),
                ('op_time', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=42, size=2)),
                ('anaesthesia_time', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=42, size=2)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ops', to='settlement.settlement')),
            ],
        ),
    ]
