# Generated by Django 4.0.2 on 2022-06-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='id',
        ),
        migrations.AlterField(
            model_name='settlement',
            name='homepage',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settlement', serialize=False, to='homepage.homepage'),
        ),
    ]
