# Generated by Django 4.0.2 on 2022-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_remove_settlement_id_alter_settlement_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='admit_path',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='admit_specialty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='age',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='case_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='cont_hosp_check',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='cont_hosp_plan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='contact_addr1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='contact_addr2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='contact_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='contact_relation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='head_injury_check',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='hosp_duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='id_card_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='id_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='nationality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='newborn_admit_weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='newborn_birth_weight',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='nurse_ic_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='physician_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='post_admit_coma',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='pre_admit_coma',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='present_addr1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='present_addr2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='profession',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='release_specialty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='release_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='release_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='trans_specialty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='work_addr1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='work_addr2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='work_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
