# Generated by Django 4.0.2 on 2022-07-25 17:01

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_mainsymp_delete_othersymp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindiag',
            name='western_release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_diag', to='settlement.westernrelease'),
        ),
        migrations.AlterField(
            model_name='mainsymp',
            name='traditional_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_symps', to='settlement.traditionalrelease'),
        ),
        migrations.AlterField(
            model_name='otherdiag',
            name='western_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_diags', to='settlement.westernrelease'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='heal_type',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=42, size=2),
        ),
    ]
