# Generated by Django 4.0.2 on 2022-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0003_settlement_admit_path_settlement_admit_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='head_injury_check',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='newborn_admit_weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='newborn_birth_weight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
