# Generated by Django 4.0.2 on 2022-07-26 11:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_alter_cuusage_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='accept_hosp_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='accept_hosp_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='blood_type',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=42, size=2),
        ),
    ]
