# Generated by Django 4.0.2 on 2022-06-28 15:49

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_alter_settlement_head_injury_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='post_admit_coma',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='pre_admit_coma',
        ),
        migrations.AlterField(
            model_name='settlement',
            name='admit_specialty',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=63, size=3),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='cont_hosp_check',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='contact_addr1',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=20), default=None, max_length=63, size=3),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='present_addr1',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=20), default=None, max_length=63, size=3),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='release_specialty',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=63, size=3),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='trans_specialty',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=63, size=3),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='work_addr1',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=20), default=None, max_length=63, size=3),
        ),
        migrations.CreateModel(
            name='PreAdmitComa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, default=0)),
                ('hrs', models.IntegerField(blank=True, default=0)),
                ('mins', models.IntegerField(blank=True, default=0)),
                ('settlement', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pre_admit_coma', to='settlement.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='PostAdmitComa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, default=0)),
                ('hrs', models.IntegerField(blank=True, default=0)),
                ('mins', models.IntegerField(blank=True, default=0)),
                ('settlement', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_admit_coma', to='settlement.settlement')),
            ],
        ),
    ]
