# Generated by Django 4.0.2 on 2022-07-26 11:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_settlement_accept_hosp_2_settlement_accept_hosp_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='settle_duration',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=42, size=2),
        ),
    ]
