# Generated by Django 4.0.2 on 2022-04-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty1',
            fields=[
                ('value', models.CharField(blank=True, default='', max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='Specialty2',
            fields=[
                ('value', models.CharField(blank=True, default='', max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
                ('specialty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty2', to='standard.specialty1')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='Specialty3',
            fields=[
                ('value', models.CharField(blank=True, default='', max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
                ('specialty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty3', to='standard.specialty2')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
    ]
