# Generated by Django 4.0.2 on 2022-04-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='Specialty2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
                ('specialty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty2', to='standard.specialty1')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='SpecialtyStd',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Specialty3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
                ('specialty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty3', to='standard.specialty2')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.AddField(
            model_name='specialty1',
            name='specialtyStd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty1', to='standard.specialtystd'),
        ),
    ]
