# Generated by Django 4.0.2 on 2022-04-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialty1',
            old_name='specialtyStd',
            new_name='specialtystd',
        ),
    ]
