# Generated by Django 4.0.2 on 2022-07-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedstds',
            name='dgstd',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applied_stds', to='standard.diagstd'),
        ),
        migrations.AlterField(
            model_name='appliedstds',
            name='spstd',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applied_stds', to='standard.specialtystd'),
        ),
    ]
