# Generated by Django 4.0.2 on 2022-07-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_applieddgstd_appliedspstd_delete_appliedstds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applieddgstd',
            old_name='spstd',
            new_name='dgstd',
        ),
    ]
