# Generated by Django 4.0.2 on 2022-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_alter_diag_pinyin_alter_diag_pinyin_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diag',
            name='label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
