# Generated by Django 4.0.2 on 2022-07-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_alter_applieddgstd_dgstd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applieddgstd',
            name='dgstd',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_dgstd', to='standard.diagstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='admit_condition_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_admit_condition_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='anaesthesia_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_anaesthesia_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='applied_admit_path_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_applied_admit_path_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='blood_group_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_blood_group_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='blood_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_blood_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='contact_relation_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_contact_relation_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='cu_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_cu_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='ethnicity_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_ethnicity_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='gender_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_gender_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='hosp_reason_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_reason_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='id_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_id_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='marriage_stat_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_marriage_stat_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='nationality_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_nationality_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='newborn_admit_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_newborn_admit_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='op_lvl_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_op_lvl_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='payment_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_payment_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='purchase_method_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_purchase_method_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='record_quality_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_record_quality_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='release_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_release_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='rh_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_rh_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='settlemenet_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_settlement_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='special_person_type_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_special_person_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedgstds',
            name='wound_healing_lvl_std',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_wound_healing_lvl_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='appliedspstd',
            name='spstd',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_spstd', to='standard.specialtystd'),
        ),
        migrations.AlterField(
            model_name='diag',
            name='code',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='diag',
            name='description',
            field=models.TextField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='diag',
            name='label',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='diag',
            name='pinyin',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='diag',
            name='pinyin_cap',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='code',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='label',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='specialty1',
            name='description',
            field=models.TextField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialty1',
            name='label',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='specialty1',
            name='value',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='specialty2',
            name='description',
            field=models.TextField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialty2',
            name='label',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='specialty2',
            name='value',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='specialty3',
            name='description',
            field=models.TextField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='specialty3',
            name='label',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='specialty3',
            name='value',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
