# Generated by Django 4.0.2 on 2022-07-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0016_gstd_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='gstd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstd', to='standard.gstd'),
        ),
    ]
