# Generated by Django 4.0.2 on 2022-07-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0017_alter_general_gstd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedgstds',
            old_name='applied_admit_path_std',
            new_name='admit_path_std',
        ),
    ]
