# Generated by Django 4.0.2 on 2022-07-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0018_rename_applied_admit_path_std_appliedgstds_admit_path_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='gstd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general', to='standard.gstd'),
        ),
    ]
