# Generated by Django 4.0.2 on 2022-07-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0019_alter_general_gstd'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedgstds',
            name='heal_type_std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heal_type_std', to='standard.gstd'),
        ),
        migrations.AlterField(
            model_name='gstd',
            name='type',
            field=models.CharField(choices=[('NATIONALITY', 'Nationality'), ('ETHNICITY', 'Ethnicity'), ('IDTYPE', 'Idtype'), ('GENDER', 'Gender'), ('MARRIAGESTAT', 'Marriagestat'), ('SETTLEMENTTYPE', 'Settlementtype'), ('CONTACTRELATION', 'Contactrelation'), ('SPECIALPERSONTYPE', 'Specialpersontype'), ('NEWBORNADMITTYPE', 'Newbornadmittype'), ('HOSPREASON', 'Hospreason'), ('HEALTYPE', 'Healtype'), ('ADMITPATH', 'Admitpath'), ('ANAESTHESIATYPE', 'Anaesthesiatype'), ('CUTYPE', 'Cutype'), ('BLOODTYPE', 'Bloodtype'), ('PAYMENTTYPE', 'Paymenttype'), ('PURCHASEMETHOD', 'Purchasemethod'), ('ADMITCONDITION', 'Admitcondition'), ('BLOODGROUP', 'Bloodgroup'), ('RH', 'Rh'), ('RECORDQUALITY', 'Recordquality'), ('OPLVL', 'Oplvl'), ('WOUNDHEALINGLVL', 'Woundhealinglvl'), ('RELEASETYPE', 'Releasetype')], default='NATIONALITY', max_length=32),
        ),
    ]
