# Generated by Django 4.0.2 on 2022-08-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0023_remove_appliedgstds_wound_healing_lvl_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedg2stds',
            name='wound_healing_lvl_std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_wound_healing_lvl_std', to='standard.g2std'),
        ),
    ]
