# Generated by Django 4.0.2 on 2022-04-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdmitComa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, default=0)),
                ('hrs', models.IntegerField(blank=True, default=0)),
                ('mins', models.IntegerField(blank=True, default=0)),
                ('homepage', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_admit_coma', to='homepage.homepage')),
            ],
        ),
    ]
