# Generated by Django 4.0.2 on 2022-06-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='newborn_birth_weight',
        ),
        migrations.AddField(
            model_name='homepage',
            name='newnewborn_birth_weight',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='newborn_admit_weight',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
