# Generated by Django 4.0.2 on 2022-08-03 10:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindiag',
            name='release',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=64), default=None, max_length=3250, size=None),
        ),
        migrations.AlterField(
            model_name='otherdiag',
            name='release',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=64), default=None, max_length=3250, size=None),
        ),
    ]
