# Generated by Django 4.0.2 on 2022-08-03 11:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_maindiag_release_alter_otherdiag_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='diagnosis',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=64), default=None, max_length=3250, size=None),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='description',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default=None, max_length=64), default=None, max_length=3250, size=None),
        ),
    ]
