# Generated by Django 4.0.2 on 2022-04-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_postadmitcoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, default=0)),
                ('self_pay', models.FloatField(blank=True, default=0)),
                ('general_service', models.FloatField(blank=True, default=0)),
                ('general_operation', models.FloatField(blank=True, default=0)),
                ('general_nursing', models.FloatField(blank=True, default=0)),
                ('general_other', models.FloatField(blank=True, default=0)),
                ('pathologic_diag', models.FloatField(blank=True, default=0)),
                ('lab_diag', models.FloatField(blank=True, default=0)),
                ('scan_diag', models.FloatField(blank=True, default=0)),
                ('clinic_diag', models.FloatField(blank=True, default=0)),
                ('non_operational', models.FloatField(blank=True, default=0)),
                ('operational', models.FloatField(blank=True, default=0)),
                ('clinic_physic', models.FloatField(blank=True, default=0)),
                ('anaesthesia', models.FloatField(blank=True, default=0)),
                ('operation', models.FloatField(blank=True, default=0)),
                ('recover', models.FloatField(blank=True, default=0)),
                ('traditional_treat', models.FloatField(blank=True, default=0)),
                ('western_med', models.FloatField(blank=True, default=0)),
                ('antibio_med', models.FloatField(blank=True, default=0)),
                ('traditional_patent_drug', models.FloatField(blank=True, default=0)),
                ('traditional_herb', models.FloatField(blank=True, default=0)),
                ('blood', models.FloatField(blank=True, default=0)),
                ('proteins', models.FloatField(blank=True, default=0)),
                ('globulins', models.FloatField(blank=True, default=0)),
                ('coagulation', models.FloatField(blank=True, default=0)),
                ('cytokine', models.FloatField(blank=True, default=0)),
                ('examine_supplies', models.FloatField(blank=True, default=0)),
                ('treat_supplies', models.FloatField(blank=True, default=0)),
                ('operation_supplies', models.FloatField(blank=True, default=0)),
                ('other', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
