# Generated by Django 4.0.2 on 2022-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_homepage_diagnosis_alter_pathology_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='maindiag',
            name='release',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='otherdiag',
            name='release',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='pathology',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
