# Generated by Django 4.0.2 on 2022-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_homepage_diagnosis_alter_maindiag_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology',
            name='description',
            field=models.TextField(blank=True, default='', max_length=64),
        ),
    ]
