# Generated by Django 4.0.2 on 2022-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_charge_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='anaesthesia_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='anaesthetist',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='assis1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='assis2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='operator',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='op',
            name='wound_healing_lvl',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
