# Generated by Django 4.0.2 on 2022-04-07 14:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_homepage_release_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='release_specialty',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=20), default=None, max_length=63, size=3),
        ),
    ]
