# Generated by Django 4.0.2 on 2022-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_homepage_release_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='release_specialty',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
